# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Grab

on:
  schedule:
    - cron: '44,45,47,47,48,49,50,51 15 * * *'
#  release:
#    types: [published]
#  push:
#    branches: [main, master]
#  pull_request:
#    branches: [main, master]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: actions/steup-python@v3
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test
        run: |
          python main.py
